Importing the dependencies


In [3]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
import seaborn

Data Collection and Pre - Processing


In [4]:
movies_data = pd.read_csv('/content/movies.csv')

In [5]:
movies_data.head(10)

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton
5      5  ...          Sam Raimi
6      6  ...       Byron Howard
7      7  ...        Joss Whedon
8      8  ...        David Yates
9      9  ...        Zack Snyder

[10 rows x 24 columns]

In [6]:
print(movies_data.columns)

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')


In [44]:
selected_features = ['genres','keywords','tagline','cast','director','overview','vote_average']

In [45]:
#replacing NULL values
for features in selected_features:
  movies_data[features] = movies_data[features].fillna('')

In [50]:
all_features = movies_data['genres']+' '+movies_data['keywords'] + ' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']+' '+movies_data['overview']+' '+str(movies_data['vote_average'])

In [51]:
print(all_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [52]:
#feature vector
vectorizer = TfidfVectorizer()
feature_vector = vectorizer.fit_transform(all_features)

In [53]:
print(feature_vector)

  (0, 10295)	0.024974283494048517
  (0, 8332)	0.024974283494048517
  (0, 294)	0.024974283494048517
  (0, 15880)	0.024974283494048517
  (0, 29331)	0.024974283494048517
  (0, 18695)	0.024974283494048517
  (0, 293)	0.024974283494048517
  (0, 292)	0.024974283494048517
  (0, 291)	0.024974283494048517
  (0, 287)	0.024974283494048517
  (0, 286)	0.024974283494048517
  (0, 5251)	0.164501420317326
  (0, 1020)	0.1224362551217366
  (0, 1249)	0.052525971081164385
  (0, 21531)	0.165928910748635
  (0, 1287)	0.031842105233375904
  (0, 19658)	0.16065161753851973
  (0, 10376)	0.13800690322028517
  (0, 2980)	0.09939854632926817
  (0, 27523)	0.14519155685385132
  (0, 2691)	0.0977164738413209
  (0, 4135)	0.061744475348772566
  (0, 18033)	0.10901815175768578
  (0, 28605)	0.15437521976048765
  (0, 19549)	0.04891455588907296
  :	:
  (4802, 12725)	0.02895570674822552
  (4802, 18963)	0.04449458525808278
  (4802, 15653)	0.07802120233626673
  (4802, 30321)	0.05767053755531514
  (4802, 4159)	0.037883601019264176
 

Cosine Similarity

In [54]:
similarity_score = cosine_similarity(feature_vector)

In [55]:
print(similarity_score)

[[1.         0.05715828 0.03941172 ... 0.03245134 0.03537253 0.01162499]
 [0.05715828 1.         0.04944841 ... 0.05546431 0.03575304 0.01942402]
 [0.03941172 0.04944841 1.         ... 0.03104632 0.0519427  0.01773275]
 ...
 [0.03245134 0.05546431 0.03104632 ... 1.         0.03843373 0.03862748]
 [0.03537253 0.03575304 0.0519427  ... 0.03843373 1.         0.03412955]
 [0.01162499 0.01942402 0.01773275 ... 0.03862748 0.03412955 1.        ]]


Taking User Inputs

In [63]:
movie_name = input('Enter movie name : ')


Enter movie name : avatar


In [64]:
list_of_titles = movies_data['title'].tolist()
print(list_of_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [65]:
close_match = difflib.get_close_matches(movie_name,list_of_titles)
print(close_match)

['Avatar']


In [66]:
index_of_movie = movies_data[movies_data.title == close_match[0]]['index'].values[0]
print(index_of_movie)

0


Getting List of similar Movies

In [67]:
similarity = list(enumerate(similarity_score[index_of_movie]))
print(similarity)

[(0, 1.0000000000000002), (1, 0.05715828007434421), (2, 0.03941172419462485), (3, 0.039557921962938655), (4, 0.09230411054410553), (5, 0.062193932311622985), (6, 0.026838329206328223), (7, 0.07273942637569315), (8, 0.02816959492848075), (9, 0.03848947179870815), (10, 0.057322237943494635), (11, 0.04054957221855954), (12, 0.02938728407816105), (13, 0.03429860574828663), (14, 0.06833340815743053), (15, 0.03947012174951719), (16, 0.04855033131536438), (17, 0.03808284109851679), (18, 0.06642902054820941), (19, 0.04149453992588339), (20, 0.036511253777528646), (21, 0.028209998633434125), (22, 0.029081039988985105), (23, 0.043847618487353635), (24, 0.034246961959713836), (25, 0.042914569770762016), (26, 0.08289187212977694), (27, 0.09514087259250777), (28, 0.0346648987574142), (29, 0.05663448515714196), (30, 0.052239191423606494), (31, 0.08030967652873633), (32, 0.04824771882046255), (33, 0.03915640470336713), (34, 0.025615825498941834), (35, 0.06526804882217963), (36, 0.08960970899991968), 

In [68]:
sorted_similarity = sorted(similarity,key = lambda x:x[1],reverse=True)
print(sorted_similarity)

[(0, 1.0000000000000002), (1914, 0.1660180651903441), (1531, 0.16344013675898547), (56, 0.15784217635793693), (3158, 0.15752825620271116), (1352, 0.15436961620794543), (2403, 0.15284631387195013), (94, 0.14719599052928742), (4401, 0.14377334319732862), (2198, 0.13698715827582517), (239, 0.13693560033545352), (461, 0.1336332295576684), (3604, 0.13276349781402924), (3730, 0.1317566632038557), (369, 0.129953075432459), (305, 0.1290975719294491), (47, 0.12803697613157206), (942, 0.12803359369644648), (342, 0.12770469807946366), (661, 0.12756085994708025), (1275, 0.12712856208113119), (150, 0.12327953650829161), (1354, 0.12296201980421978), (300, 0.1214089892791662), (432, 0.12036266219893418), (1759, 0.11854334799150504), (43, 0.1182490863959503), (529, 0.11819803971283588), (549, 0.11804145509800543), (2995, 0.11803544053853035), (4593, 0.11708915951258898), (311, 0.1164816586728467), (2696, 0.11534640608913951), (4332, 0.1153273250068642), (1053, 0.11454289407270325), (775, 0.11394171741

In [69]:
print('Movies Suggested : \n')
counter = 1
for x in sorted_similarity:
  index = x[0]
  title = movies_data[movies_data.index==index]['title'].values[0]
  if(counter<21):
    print(counter,' ',title)
    counter+=1

Movies Suggested : 

1   Avatar
2   Lifeforce
3   Moonraker
4   Star Trek Beyond
5   Alien
6   Gattaca
7   Aliens
8   Guardians of the Galaxy
9   The Helix... Loaded
10   Lockout
11   Gravity
12   Lost in Space
13   Apollo 18
14   Cargo
15   Lara Croft Tomb Raider: The Cradle of Life
16   Treasure Planet
17   Star Trek Into Darkness
18   The Book of Life
19   Men in Black
20   Zathura: A Space Adventure
